FROM centos:7

RUN yum install -yy bind-utils \
	binutils-devel \
	bzip2-devel \
	elfutils-libelf-devel \
	elfutils-devel \
	file \
	gcc \
	gcc-c++ \
	git \
	iproute \
	jq \
	libdwarf-devel \
	libstdc++-static \
	libzstd-devel \
	lz4-devel \
	make \
	openssl-devel \
	pkg-config \
	psmisc \
	snappy-devel \
	unzip \
	wget \
	which \
	zlib-devel

RUN curl -L https://cmake.org/files/v3.10/cmake-3.10.3.tar.gz -o cmake-3.10.3.tar.gz \
	&& tar xzf cmake-3.10.3.tar.gz \
	&& cd cmake-3.10.3 \
	&& ./bootstrap \
	&& make \
	&& make install \
	&& cmake --version \
	&& rm -rf /cmake-3.10.3.tar.gz /cmake-3.10.3

RUN curl -L https://github.com/gflags/gflags/archive/v2.1.2.tar.gz -o gflags.tar.gz \
	&& tar xf gflags.tar.gz \
	&& cd gflags-2.1.2 \
	&& cmake . \
	&& make -j \
	&& make install \
	&& rm -rf /gflags.tar.gz /gflags-2.1.2

RUN curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/protoc-3.3.0-linux-x86_64.zip \
	&& unzip -o protoc-3.3.0-linux-x86_64.zip -d /usr/local bin/protoc \
	&& rm -f protoc-3.3.0-linux-x86_64.zip

ENV GOLANG_VERSION 1.12
ENV GOLANG_DOWNLOAD_URL https://dl.google.com/go/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 750a07fef8579ae4839458701f4df690e0b20b8bcce33b437e4df89c451b6f13

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
	&& echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
	&& tar -C /usr/local -xzf golang.tar.gz \
	&& rm golang.tar.gz

ENV GOPATH /go
ENV GOROOT /usr/local/go
ENV PATH $GOPATH/bin:$GOROOT/bin:$PATH

ENV RUSTUP_HOME /rust
ENV CARGO_HOME /rust

RUN curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path --default-toolchain nightly-2019-06-14 -y

ENV PATH $CARGO_HOME/bin:$RUSTUP_HOME/bin:$PATH

RUN rustup component add rustfmt-preview
RUN rustup component add clippy-preview

# Add serf and tidb binaries for testing purpose
RUN wget https://releases.hashicorp.com/serf/0.8.2/serf_0.8.2_linux_amd64.zip \
	&& unzip serf_0.8.2_linux_amd64.zip \
	&& mv serf /usr/local/bin/serf \
	&& rm serf_0.8.2_linux_amd64.zip
RUN wget http://download.pingcap.org/tidb-v3.0.2-linux-amd64.tar.gz \
	&& tar xzf tidb-v3.0.2-linux-amd64.tar.gz \
	&& mv tidb-v3.0.2-linux-amd64/bin/* /usr/local/bin/ \
	&& rm -r tidb-v3.0.2-linux-amd64 tidb-v3.0.2-linux-amd64.tar.gz
